final case class PropertyAd(id: String,
                           project_name: String,
                           developer: String,
                           city: String,
                           district: String,
                           address: String,
                           full_address: String,
                           property_type: String,
                           status: String,
                           size: Double,
                           size_range: String,
                           number_of_rooms: Int,
                           floor: Int,
                           price: Double,
                           price_per_sqm: Double,
                           price_range: String,
                           project_link: String,
                           apartment_link: String,
                           date: String)

final case class PropertyAdClean(id: String,
                            project_name: String,
                            developer: String,
                            city: String,
                            district: String,
                            address: String,
                            property_type: String,
                            status: String,
                            size: Double,
                            number_of_rooms: Int,
                            floor: Int,
                            price: Double,
                            price_per_sqm: Double,
                            project_link: String,
                            apartment_link: String,
                            date: String)