final case class PropertyAdClean(ad_id: Int,
                           id: String,
                           project_name: String,
                           developer: String,
                           city: String,
                           district: String,
                           address: String,
                           property_type: String,
                           status: String,
                           size: Double,
                           number_of_rooms: Int,
                           floor: Int,
                           price: Double,
                           price_per_sqm: Double,
                           project_link: String,
                           apartment_link: String,
                           date: String)